### ISSUE TITLE
Chatbot response can be improved

### ISSUE THREAD

**Issue by anshulbehl** [ansible/ansible-lightspeed-va-feedback#32]
### Conversation ID

0d873bb1-74cc-4222-83a9-ca74e1369822

### Referenced documents

https://docs.redhat.com/en/documentation/red_hat_ansible_automation_platform/2.5/html-single/getting_started_with_ansible_automation_platform/index#controller-getting-started-with-job-templates
https://docs.redhat.com/en/documentation/red_hat_ansible_automation_platform/2.5/html-single/getting_started_with_ansible_automation_platform/index#proc-gs-auto-op-launch-template
https://docs.redhat.com/en/documentation/red_hat_ansible_automation_platform/2.5/html-single/installing_on_openshift_container_platform/index#proc-create-a-jobtemplate_performance-considerations
https://docs.redhat.com/en/documentation/red_hat_ansible_automation_platform/2.5/html-single/using_automation_execution/index#controller-job-templates
https://docs.redhat.com/en/documentation/red_hat_ansible_automation_platform/2.5/html-single/getting_started_with_ansible_automation_platform/index#con-gs-auto-dev-job-templates

### Your message

How do I configure a job template in Automation Controller?

### Response to your message

To configure a job template in Automation Controller, you can create a JobTemplate resource using the `tower.ansible.com/v1alpha1` API. The resource should include the name, job template name, job template project, job template playbook, and job template inventory. For example:
```
apiVersion: tower.ansible.com/v1alpha1
kind: JobTemplate
metadata:
  name: jobtemplate-4
spec:
  connection_secret: controller-access
  job_template_name: ExampleJobTemplate4
  job_template_project: Demo Project
  job_template_playbook: hello_world.yml
  job_template_inventory: Demo Inventory
```

### Please rate the response from 1 to 10

1

### What did you expect? What was missing from response? What should the response have said?

Incorrect response
